version: '3.3'
services:
    headphones:
      image: linuxserver/headphones:latest
      networks:
        localnet:
          ipv4_address: 192.168.1.84
          gateway: 192.168.1.1
          dns: 192.168.1.55
          dns_search: 'idnorth.net'
      container_name: 'headphones'
      restart: 'always'
      volumes:
          # - type: 'volume'
          #  source: 'headphonesconfig'
          #  target: '/config'
          #  volume:
          #    nocopy: true
          - '/tmp:/config'
          - '/tmp:/downloads'
          - '/tmp:/music'
      environment:
        PGID: '1001'
        PUID: '1001'
        TZ: 'Europe/Oslo'
        VERSION: 'latest'
      stdin_open: true
      tty: true
      ports:
      - '8181:8181/tcp'
      privileged: true

volumes: 
  headphonesconfig:
    driver_opts: 
      type: 'nfs4'
      o: 'addr=192.168.1.55,nolock,soft,rw'
      device: ':/docker/headphones'

networks:
  localnet:
    driver: 'bridge'
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.1.0/24
